package app.yydarlinker.deepseekcaptions;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;import org.json.*;
public class EditorialBaseline107Test {
 private AnchoredCaptionPlan.Segment s(int i,long a,long b,String t){return new AnchoredCaptionPlan.Segment(i,i,a,b,t);}
 @Test public void noSemanticPermissionMeansNoJoin(){List<AnchoredCaptionPlan.Segment> a=Arrays.asList(s(0,0,600,"对。"),s(1,600,1600,"第二点"));assertEquals(2,EditorialCaptionPlan.pack(a,null).size());assertEquals(2,EditorialCaptionPlan.pack(a,new JSONArray().put(9).put("wrong")).size());}
 @Test public void shortRelatedEventsJoinWithoutChangingClockOrWords(){List<AnchoredCaptionPlan.Segment>a=Arrays.asList(s(0,0,800,"这会降低成本，"),s(1,800,3000,"并方便量产。"));List<AnchoredCaptionPlan.Segment> b=EditorialCaptionPlan.pack(a,new JSONArray().put(0));assertEquals(1,b.size());assertEquals("这会降低成本，并方便量产。",b.get(0).text);assertEquals(0,b.get(0).startMs);assertEquals(3000,b.get(0).endMs);}
 @Test public void lengthDurationAndPauseAllGuardPacking(){for(List<AnchoredCaptionPlan.Segment>a:Arrays.asList(Arrays.asList(s(0,0,800,"因此"),s(1,1200,3000,"这不合适。")),Arrays.asList(s(0,0,800,"因此"),s(1,800,7100,"这不合适。")),Arrays.asList(s(0,0,800,"因此"),s(1,800,3000,String.join("",Collections.nCopies(40,"字"))))))assertEquals(2,EditorialCaptionPlan.pack(a,new JSONArray().put(0)).size());}
 @Test public void comfortableEventsAreNotPackedToFillSpace(){assertEquals(2,EditorialCaptionPlan.pack(Arrays.asList(s(0,0,2500,"First thought."),s(1,2500,5000,"Next thought.")),new JSONArray().put(0)).size());}
 @Test public void sameRulesWorkBeyondChinese(){List<AnchoredCaptionPlan.Segment>a=Arrays.asList(s(0,0,800,"This reduces cost"),s(1,800,3000,"and simplifies production."));assertEquals(1,EditorialCaptionPlan.pack(a,new JSONArray().put(0)).size());assertEquals(2,EditorialCaptionPlan.pack(a,null).size());}
 private List<SourceAtomTimeline.Atom> atoms(){List<SourceAtomTimeline.Atom>a=new ArrayList<>();for(int i=0;i<8;i++)a.add(new SourceAtomTimeline.Atom(i*500,(i+1)*500,"word"+i,i,true));return a;}
 private TranslationUnitTimeline.Unit unit(List<SourceAtomTimeline.Atom>a){return AnchoredWindowPlanner.build(new SourceAtomTimeline.Result(a,8,8,0,true,false)).units.get(0);}
 @Test public void optionalMetadataIsNotARejectionOrRetry()throws Exception{List<SourceAtomTimeline.Atom>a=atoms();TranslationUnitTimeline.Unit u=unit(a);String row=new JSONObject().put("id",u.id).put("segments",new JSONArray().put(new JSONArray().put(7).put("这是完整且有效的翻译。"))).put("join_after","unsupported optional shape").toString();ContextualBatchApiClient.Result r=ContextualBatchApiClient.parseAnchored("{\"translations\":["+row+"]}",Arrays.asList(u),a);assertEquals(1,r.validCount());}
 @Test public void cacheRoundTripDoesNotApplyOldTimingOnlyMerge()throws Exception{List<SourceAtomTimeline.Atom>a=atoms();TranslationUnitTimeline.Unit u=unit(a);AnchoredCaptionPlan p=AnchoredCaptionPlan.parse(new JSONArray("[[0,\"是的。\"],[7,\"这是第二个完整意思。\"]]"),a,u);assertEquals(2,p.segments.size());assertEquals(p.toJson().toString(),AnchoredCaptionPlan.parse(p.toJson(),a,u).toJson().toString());}
 @Test public void structuralFailuresStillFail()throws Exception{List<SourceAtomTimeline.Atom>a=atoms();try{AnchoredCaptionPlan.parse(new JSONArray("[[3,\"遗漏一半源文本\"]]"),a,unit(a),new JSONArray().put(3));fail();}catch(IllegalArgumentException expected){assertTrue(expected.getMessage().contains("incomplete"));}}
 @Test public void outputAndInputCostsStayBounded(){List<SourceAtomTimeline.Atom>a=new ArrayList<>();for(int i=0;i<40;i++)a.add(new SourceAtomTimeline.Atom(i*600,i*600+200,"word",i,true));TranslationUnitTimeline.Unit u=new TranslationUnitTimeline.Unit(0,"t",0,39,0,39,0,24000,"words",TranslationUnitTimeline.Confidence.MEDIUM,"test");assertEquals(8,EditorialCaptionPlan.pauses(a,u).length());assertEquals(3,AnchoredRetryPolicy.MAX_FAILURES);}
}
